### ISSUE TITLE
co robimy

### ISSUE THREAD

**Issue by woru** [thuliumcc/dartboard#1]
Post na /hit z polem 15d (s/d/t dla single double triple) dodaje punkty dla gry z najwiekszym id dla usera z current_game_user_id

na stronie index jest refresh ajaxem stanu gry co 500 ms (kiedys zrobimy long_poll)

**Comment by piotrooo** [comment]
to co zamiast na ouzo to na node.js? framework sails.js ?

**Comment by woru** [comment]
long_poll po prostu przez 12s w petli czyta eventy i jak jakis jest to go wysyla. W sesji zapisany timestamp ostatniego przetworzonego eventu. W GUI możemy też mieć log eventów. Eventy będą kasowane po kliknieciu nowa gra.

Każde wywołanie long_polla w petli wczytuje eventy nowsze niż timestamp z sesji.

**Comment by woru** [comment]
Na stronie głównej osobny przycisk dla każdego typu gry.
Po kliknieciu nowa gra można od razu przejść do strony gry gdzie będzie tabelka z rankingiem i kolejnością. Z boku będzie lista userów. Po kliknieciu na usera pojdzie ajax i doda go do gry (nie trzeba bedzie robic selectlisty).

W tabelce z rankingiem będzie (dla krykieta) username, kolumny z iląscią zamkniętych pól, całkowity progres, chart z ilością zamkniętych w każdej rundzie (http://mleibman.github.io/SlickGrid/examples/example10-async-post-render.html)

**Comment by woru** [comment]
nowa tabelka z hit z id game_user i numerem rundy i score z rundy, do game dodac kolumne runda

**Comment by woru** [comment]
wycofałbym zmiane users na players i zrobił:
users - wszyscy
players - GameUser czyli user ktory bierze udział w grze

**Comment by woru** [comment]
session_open jest stasznie wolne

**Comment by woru** [comment]
https://github.com/letsdrink/ouzo/issues/217

**Comment by woru** [comment]
trzeba zrobić gdzieś:
 Pozostałe rzuty: ***

**Comment by woru** [comment]
walidacja ze 3 rzuty

**Comment by woru** [comment]
czasem po przeladowaniu serwer nie wie ze polaczenie sie skonczylo i zjadane są eventy

**Comment by woru** [comment]
na http://localhost/dartboard/test/ mozna symulowac rzuty
