### ISSUE TITLE
nie wywalac gry po zakonczeniu. 

### ISSUE THREAD

**Issue by woru** [thuliumcc/dartboard#4]
Game::currentGame ma zwracać ostatnią ale tylko jeśli ma finished == false
Dodatkowo trzeba dodać kolumne winner

**Comment by piotrooo** [comment]
chyba będzie ok :)

**Comment by woru** [comment]
jak probowalem to zrobic to okazalo sie ze trzeba zrobic tworzenie gry w jednym kroku.
Tak zeby bylo normalnie strona game new i post na create. Innaczej byl problem z automatycznym przekierowaniem na stronę bieżącej gry bo mogło przekierować zanim byli dodani gracze.

**Comment by piotrooo** [comment]
czyli co jest źle?

**Comment by woru** [comment]
jeszcze nie klikalem, tylko pisze z czym ja mialem problem
